### ISSUE TITLE
Game freezes before window opens with no errors

### ISSUE THREAD

**Issue by FrostBird347** [LudoCrypt/Backrooms#2]
Versions confirmed to be affected: 1.3.1, 1.3.0

Versions confirmed to be unaffected: None

What you were doing (ingame) when the issue occurred?: Launched, application window has not opened yet.

What is the issue?: The game stops launching after showing the log `Backend library: LWJGL version 3.2.1 build 12`, with it using around 250% cpu for a few minutes, before dropping down at a decreasing rate (0.12% within 5 mins, 0.08% after 30 mins and still decreasing) and never launching, or outputting any other logs. 

What other mods do you have installed?: I have verified that all the dependencies were installed and I tried launching the mod with only the dependencies and the mod itself installed.

Log/Crash report?: [latest.log](https://github.com/LudoCrypt/Backrooms/files/5282145/latest.log)

Any additional information?: Nothing that I can think of.

**Comment by FrostBird347** [comment]
Renaming `minecraft/config`, launching the game, quitting and replacing the new config folder with the old config folder somehow fixed the issue.

**Comment by LudoCrypt** [comment]
Due to java.awt. Fixed in development version
