### ISSUE TITLE
Curios API + Backrooms messes up creative mode menu

### ISSUE THREAD

**Issue by Yegiyan** [LudoCrypt/Backrooms#3]
**Versions confirmed to be affected:** 1.3.1
**Versions confirmed to be unaffected:** N/A

**What you were doing (ingame) when the issue occurred?:** Launch the game and go into creative mode.

**What is the issue?:** When I install The Backrooms alongside Curious API and  go into creative mode almost all default Minecraft items/blocks are gone, though their respective tabs are still there... empty. I isolated down to Backrooms as other mods weren't causing this issue. 

**What other mods do you have installed?:** Only the 'Fabric API 0.23 Build 410' and 'Curios API 0.0.8'

**Log/Crash report?:** 

w/o warnings: https://paste.ubuntu.com/p/p52j25Yz85/
with warnings: https://paste.ubuntu.com/p/nKfsxcCmhD/

**Any additional information?:** Nothing that I can think of.

**Comment by LudoCrypt** [comment]
Update https://www.curseforge.com/minecraft/mc-mods/cardinal-components
