### ISSUE TITLE
Help Project Managing

### ISSUE THREAD

**Issue by crabdancing** [LudoCrypt/Backrooms#7]
I don't mean to be rude, but do you need help managing this project? I'm seeing a lot of problems both in the repo and in the code quality.

**Comment by crabdancing** [comment]
I'd love to help if you need it. I think your mod is awesome :)

**Comment by LudoCrypt** [comment]
I know about the issues in code and such, I am working on a complete rewrite. If you wanted to help, id gladly take some!

**Comment by LudoCrypt** [comment]
you can join my discord server for better communication!

**Comment by crabdancing** [comment]
Sure :)

**Comment by crabdancing** [comment]
BTW I already polished up your toolchain a bit in my fork :D
